# Niomar Lopez

## NumPy Arrays and Indexing Challenge

In [1]:
import numpy as np

## Q1 - 2 

1. Create a numpy array called ‘height in inches’ from a list 10 of numbers: [66, 68, 71, 64, 61, 74, 64, 65, 70, 71].
2. Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.

In [2]:
# Creating an array with the given values
height_in_inches = np.array([66, 68, 71, 64, 61, 74, 64, 65, 70, 71])

# Creating a new array that'll be created from taking the height in inches and dividing them by 12 to get height in feet.
height_in_feet = (height_in_inches / 12)

# Returning the new array 'height_in_feet'
height_in_feet

array([5.5       , 5.66666667, 5.91666667, 5.33333333, 5.08333333,
       6.16666667, 5.33333333, 5.41666667, 5.83333333, 5.91666667])

## Q3

Create a 5x5 array of zeros

In [3]:
arr_z = np.zeros((5,5))

arr_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Q4

Create an array of random floating point numbers between 0 and 100. 

In [4]:
arr_float = np.linspace(0,100,30)

print(arr_float)
print("The data type for this array is: " , arr_float.dtype)

[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]
The data type for this array is:  float64


## Q5

Create an array of numbers from 0 to 75 in increments of 5.

**_ASUMING THAT 75 IS INCLUSIVE_**

In [5]:
arr_incr = np.arange(0,75.5,5)

arr_incr

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75.])

# Mini Challenge - NumPy

In [6]:
import numpy as np

## Q1

Using the following array, print the **4th element in the 2nd row**<br>

`arr = np.array([[10,20,30,40,50], [600,700,800,900,1000]])`

In [7]:
arr = np.array([[10,20,30,40,50], [600,700,800,900,1000]])

print(arr[1,3])

900


## Q2

Using the following array, what index would you use to return the value of ‘10’<br>
`arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])`


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1,1,0])

10


## Q3

Create an array of 15 numbers evenly spaced between 0 and 140


In [9]:
arr3 = np.linspace(0, 140, 15)  #3rd argument in `linspace` referes to the num of elements you want returned; on it's own, python will do the equally spaced incrimentations

print(arr3)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120. 130.
 140.]


## Q4

Create an array numbers evenly spaced between 0 and 10 incremented by 0.5 


In [10]:
arr4 = np.arange(0, 10.5, .5) #Assuming that the 10 is inclusive

print(arr4)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
